version: '2'
services:
  sshd:
    build: .
    ports:
    - "44422:22"
    volumes:
    - "./code:/code"
    - "~/.ssh/id_ed25519.pub:/root/.ssh/authorized_keys:ro"
    - "~/.ssh/id_ed25519.pub:/home/rabbit/.ssh/authorized_keys:ro"
